<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Weekly Feedback Summary</title>
</head>
<body style="font-family: Arial, sans-serif; background-color: #f6f9fc; margin: 0; padding: 20px;">

    <table width="100%" cellpadding="0" cellspacing="0">
        <tr>
            <td align="center">
                <table width="600" cellpadding="20" cellspacing="0" style="background-color: #ffffff; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1);">
                    <tr>
                        <td style="text-align: center; background-color: #004aad; color: #ffffff; padding: 20px; border-top-left-radius: 8px; border-top-right-radius: 8px;">
                            <h1 style="margin: 0; font-size: 24px;">Weekly Feedback Summary</h1>
                            <p style="margin: 0; font-size: 14px;">{{ \Carbon\Carbon::now()->format('F j, Y') }}</p>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 30px; color: #333;">
                            <p style="font-size: 16px;">Here is the summary of feedback received in the past week:</p>

                            <table width="100%" cellpadding="10" cellspacing="0" style="background-color: #f2f4f8; border-radius: 5px; margin-top: 20px;">
                                <tr>
                                    <td><strong>Total Feedback</strong></td>
                                    <td>{{ $data['total'] }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Complaints Reported</strong></td>
                                    <td>{{ $data['complaints'] }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Average Satisfaction Rating</strong></td>
                                    <td>{{ number_format($data['average_rating'], 2) }}</td>
                                </tr>
                            </table>

                            @if(!empty($data['topIssues']))
                                <h3 style="margin-top: 30px;">Most Common Issues</h3>
                                <ul>
                                    @foreach($data['topIssues'] as $issue)
                                        <li>{{ $issue }}</li>
                                    @endforeach
                                </ul>
                            @endif

                            <p style="margin-top: 30px; font-size: 14px;">This summary is auto-generated by the AUSQMS system.</p>
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: center; font-size: 12px; color: #888;">
                            &copy; {{ date('Y') }} AUSQMS | Lab Management Team
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

</body>
</html>
